version: '3.8'
services: 
  sql-server:
    build:
      context: .
      dockerfile:  dockerfile
      args:
        SA_PASSWORD: YourStrong!Passw0rd
    ports:
      - 1433:1433
    user: root
    volumes:
      - ./data:/var/opt/mssql/data